name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: uv sync
      
      - name: Check formatting
        run: uv tool run ruff format --check .
      
      - name: Lint check
        run: uv tool run ruff check .
      
      - name: Run tests
        run: uv run pytest